# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userinfo_friends_+', to='app01.UserInfo', verbose_name='朋友们'),
        ),
    ]
